const LEADERBOARD_DATA = [
  {
    id: 1,
    rank: 1,
    name: "Marcus Chen",
    avatarInitials: "MC",
    avatarColor: "#4f46e5",
    score: 547,
    categories: { lab: 21, reg: 30, uni: 20, edu: 41 },
    department: "Data Engineering",
    year: 2025,
    quarter: "Q2"
  },
  {
    id: 2,
    rank: 2,
    name: "Priya Sharma",
    avatarInitials: "PS",
    avatarColor: "#0891b2",
    score: 338,
    categories: { lab: 8, reg: 28, uni: 12, edu: 14 },
    department: "ML Research",
    year: 2025,
    quarter: "Q1"
  },
  {
    id: 3,
    rank: 3,
    name: "Lena Müller",
    avatarInitials: "LM",
    avatarColor: "#be185d",
    score: 332,
    categories: { lab: 10, reg: 20, uni: 14, edu: 20 },
    department: "Product Analytics",
    year: 2024,
    quarter: "Q4"
  },
  {
    id: 4,
    rank: 4,
    name: "James Okafor",
    avatarInitials: "JO",
    avatarColor: "#15803d",
    score: 267,
    categories: { lab: 9, reg: 18, uni: 12, edu: 9 },
    department: "Cloud Infrastructure",
    year: 2025,
    quarter: "Q2"
  },
  {
    id: 5,
    rank: 5,
    name: "Sofia Bergström",
    avatarInitials: "SB",
    avatarColor: "#b45309",
    score: 253,
    categories: { lab: 13, reg: 14, uni: 9, edu: 15 },
    department: "Data Engineering",
    year: 2024,
    quarter: "Q3"
  },
  {
    id: 6,
    rank: 6,
    name: "Aiden Walsh",
    avatarInitials: "AW",
    avatarColor: "#7c3aed",
    score: 246,
    categories: { lab: 9, reg: 16, uni: 9, edu: 14 },
    department: "Security Operations",
    year: 2025,
    quarter: "Q1"
  },
  {
    id: 7,
    rank: 7,
    name: "Nora Petrov",
    avatarInitials: "NP",
    avatarColor: "#0f766e",
    score: 193,
    categories: { lab: 11, reg: 11, uni: 7, edu: 9 },
    department: "ML Research",
    year: 2023,
    quarter: "Q4"
  },
  {
    id: 8,
    rank: 8,
    name: "Diego Reyes",
    avatarInitials: "DR",
    avatarColor: "#c2410c",
    score: 187,
    categories: { lab: 7, reg: 13, uni: 6, edu: 11 },
    department: "DevOps Platform",
    year: 2024,
    quarter: "Q1"
  },
  {
    id: 9,
    rank: 9,
    name: "Yuki Tanaka",
    avatarInitials: "YT",
    avatarColor: "#0369a1",
    score: 182,
    categories: { lab: 10, reg: 8, uni: 8, edu: 10 },
    department: "Product Analytics",
    year: 2025,
    quarter: "Q3"
  },
  {
    id: 10,
    rank: 10,
    name: "Fatima Al-Rashid",
    avatarInitials: "FA",
    avatarColor: "#4d7c0f",
    score: 175,
    categories: { lab: 7, reg: 10, uni: 6, edu: 13 },
    department: "Data Engineering",
    year: 2024,
    quarter: "Q2"
  },
  {
    id: 11,
    rank: 11,
    name: "Connor MacAllister",
    avatarInitials: "CM",
    avatarColor: "#9f1239",
    score: 142,
    categories: { lab: 4, reg: 8, uni: 6, edu: 10 },
    department: "Cloud Infrastructure",
    year: 2023,
    quarter: "Q2"
  },
  {
    id: 12,
    rank: 12,
    name: "Zara Okonkwo",
    avatarInitials: "ZO",
    avatarColor: "#1d4ed8",
    score: 133,
    categories: { lab: 7, reg: 9, uni: 3, edu: 9 },
    department: "Security Operations",
    year: 2025,
    quarter: "Q4"
  },
  {
    id: 13,
    rank: 13,
    name: "Henrik Lindqvist",
    avatarInitials: "HL",
    avatarColor: "#065f46",
    score: 126,
    categories: { lab: 4, reg: 9, uni: 4, edu: 8 },
    department: "ML Research",
    year: 2024,
    quarter: "Q3"
  },
  {
    id: 14,
    rank: 14,
    name: "Amara Diallo",
    avatarInitials: "AD",
    avatarColor: "#6d28d9",
    score: 117,
    categories: { lab: 3, reg: 7, uni: 6, edu: 5 },
    department: "DevOps Platform",
    year: 2023,
    quarter: "Q1"
  },
  {
    id: 15,
    rank: 15,
    name: "Ethan Brooks",
    avatarInitials: "EB",
    avatarColor: "#0e7490",
    score: 109,
    categories: { lab: 4, reg: 8, uni: 3, edu: 7 },
    department: "Product Analytics",
    year: 2025,
    quarter: "Q2"
  },
  {
    id: 16,
    rank: 16,
    name: "Valentina Cruz",
    avatarInitials: "VC",
    avatarColor: "#a16207",
    score: 97,
    categories: { lab: 7, reg: 5, uni: 3, edu: 5 },
    department: "Data Engineering",
    year: 2024,
    quarter: "Q4"
  },
  {
    id: 17,
    rank: 17,
    name: "Rohan Mehta",
    avatarInitials: "RM",
    avatarColor: "#166534",
    score: 93,
    categories: { lab: 6, reg: 5, uni: 3, edu: 5 },
    department: "Cloud Infrastructure",
    year: 2023,
    quarter: "Q3"
  },
  {
    id: 18,
    rank: 18,
    name: "Ingrid Hansen",
    avatarInitials: "IH",
    avatarColor: "#7e22ce",
    score: 87,
    categories: { lab: 6, reg: 4, uni: 3, edu: 5 },
    department: "Security Operations",
    year: 2025,
    quarter: "Q1"
  },
  {
    id: 19,
    rank: 19,
    name: "Kwame Asante",
    avatarInitials: "KA",
    avatarColor: "#0c4a6e",
    score: 79,
    categories: { lab: 4, reg: 4, uni: 3, edu: 5 },
    department: "ML Research",
    year: 2024,
    quarter: "Q1"
  },
  {
    id: 20,
    rank: 20,
    name: "Mia Johansson",
    avatarInitials: "MJ",
    avatarColor: "#854d0e",
    score: 73,
    categories: { lab: 4, reg: 3, uni: 3, edu: 5 },
    department: "DevOps Platform",
    year: 2023,
    quarter: "Q4"
  },
  {
    id: 21,
    rank: 21,
    name: "Omar Hassan",
    avatarInitials: "OH",
    avatarColor: "#3b0764",
    score: 67,
    categories: { lab: 3, reg: 4, uni: 2, edu: 5 },
    department: "Product Analytics",
    year: 2025,
    quarter: "Q3"
  },
  {
    id: 22,
    rank: 22,
    name: "Chloe Dubois",
    avatarInitials: "CD",
    avatarColor: "#134e4a",
    score: 61,
    categories: { lab: 3, reg: 3, uni: 2, edu: 5 },
    department: "Data Engineering",
    year: 2024,
    quarter: "Q2"
  },
  {
    id: 23,
    rank: 23,
    name: "Tariq Winters",
    avatarInitials: "TW",
    avatarColor: "#78350f",
    score: 58,
    categories: { lab: 3, reg: 3, uni: 2, edu: 4 },
    department: "Cloud Infrastructure",
    year: 2023,
    quarter: "Q2"
  },
  {
    id: 24,
    rank: 24,
    name: "Elena Volkov",
    avatarInitials: "EV",
    avatarColor: "#1e1b4b",
    score: 54,
    categories: { lab: 2, reg: 3, uni: 2, edu: 4 },
    department: "Security Operations",
    year: 2024,
    quarter: "Q3"
  },
  {
    id: 25,
    rank: 25,
    name: "Felix Andersen",
    avatarInitials: "FAN",
    avatarColor: "#064e3b",
    score: 51,
    categories: { lab: 2, reg: 2, uni: 2, edu: 5 },
    department: "ML Research",
    year: 2023,
    quarter: "Q1"
  }
];
